export const estados = [
  { codigo: 12, uf: 'Acre' },
  { codigo: 27, uf: 'Alagoas' },
  { codigo: 16, uf: 'Amapá' },
  { codigo: 13, uf: 'Amazonas' },
  { codigo: 29, uf: 'Bahia' },
  { codigo: 23, uf: 'Ceará' },
  { codigo: 53, uf: 'Distrito Federal' },
  { codigo: 32, uf: 'Espírito Santo' },
  { codigo: 52, uf: 'Goiás' },
  { codigo: 21, uf: 'Maranhão' },
  { codigo: 51, uf: 'Mato Grosso' },
  { codigo: 50, uf: 'Mato Grosso do Sul' },
  { codigo: 31, uf: 'Minas Gerais' },
  { codigo: 15, uf: 'Pará' },
  { codigo: 25, uf: 'Paraíba' },
  { codigo: 41, uf: 'Paraná' },
  { codigo: 26, uf: 'Pernambuco' },
  { codigo: 22, uf: 'Piauí' },
  { codigo: 33, uf: 'Rio de Janeiro' },
  { codigo: 24, uf: 'Rio Grande do Norte' },
  { codigo: 43, uf: 'Rio Grande do Sul' },
  { codigo: 11, uf: 'Rondônia' },
  { codigo: 14, uf: 'Roraima' },
  { codigo: 42, uf: 'Santa Catarina' },
  { codigo: 35, uf: 'São Paulo' },
  { codigo: 28, uf: 'Sergipe' },
  { codigo: 17, uf: 'Tocantins' },
];

export const modelos = [
  { codigo: 55, modelo: 'NF-e' },
  { codigo: 57, modelo: 'CT-e' },
  { codigo: 58, modelo: 'MDF-e' },
  { codigo: 65, modelo: 'NFC-e' },
];
